/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#FBFAF3",
        "background-light": "#FBFAF3",
        "background-dark": "#0A0A0A",
        /* WiNote palette */
        "wn-bg": "var(--wn-bg)",
        "wn-bg-light": "var(--wn-bg-light)",
        "wn-card-green": "var(--wn-card-green)",
        "wn-card-green-light": "var(--wn-card-green-light)",
        "wn-card-yellow": "var(--wn-card-yellow)",
        "wn-card-yellow-light": "var(--wn-card-yellow-light)",
        "wn-card-lavender": "var(--wn-card-lavender)",
        "wn-card-gray": "var(--wn-card-gray)",
        "wn-accent-green": "var(--wn-accent-green)",
        "wn-accent-green-dark": "var(--wn-accent-green-dark)",
        "wn-premium-gold": "var(--wn-premium-gold)",
        "wn-text-primary": "var(--wn-text-primary)",
        "wn-text-secondary": "var(--wn-text-secondary)",
        "wn-text-tertiary": "var(--wn-text-tertiary)",
        "wn-text-accent": "var(--wn-text-accent)",
        "wn-text-danger": "var(--wn-text-danger)",
        "wn-border": "var(--wn-border)",
        "wn-divider": "var(--wn-divider)",
        "wn-overlay": "var(--wn-overlay)",
        "wn-white": "var(--wn-white)",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        wn: ["Inter", "system-ui", "-apple-system", "sans-serif"],
      },
      fontSize: {
        "wn-xs": "var(--wn-text-xs)",
        "wn-sm": "var(--wn-text-sm)",
        "wn-base": "var(--wn-text-base)",
        "wn-md": "var(--wn-text-md)",
        "wn-lg": "var(--wn-text-lg)",
        "wn-xl": "var(--wn-text-xl)",
        "wn-2xl": "var(--wn-text-2xl)",
        "wn-3xl": "var(--wn-text-3xl)",
      },
      borderRadius: {
        DEFAULT: "4px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "24px",
        "4xl": "32px",
        "5xl": "40px",
        "wn-sm": "var(--wn-radius-sm)",
        "wn-md": "var(--wn-radius-md)",
        "wn-lg": "var(--wn-radius-lg)",
        "wn-xl": "var(--wn-radius-xl)",
        "wn-2xl": "var(--wn-radius-2xl)",
        "wn-pill": "var(--wn-radius-pill)",
      },
      boxShadow: {
        "wn-card": "var(--wn-shadow-card)",
        "wn-card-sm": "var(--wn-shadow-card-sm)",
        "wn-inset": "var(--wn-shadow-inset)",
        "wn-btn": "var(--wn-shadow-btn)",
        "wn-fab": "var(--wn-shadow-fab)",
      },
      animation: {
        "spin-slow": "spin 3s linear infinite",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
